# Author - Harshad Kale
# harshad.kale@gmail.com
# https://github.com/kalehv
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#   find the sum of the even-valued terms.

__author__ = 'Harshad Kale'


def fibonacci():
    n1 = 1
    n2 = 2
    new = 1
    sum = 2
    while n1 < 4000000:
        new = n1 + n2
        if new % 2 == 0:
            sum += new
        n1 = n2
        n2 = new

    print(sum)


def main():
    fibonacci()

if __name__ == "__main__":
    main()
